name: release_to_copr

on:
  push:
    tags:
      - '**.microshift-20**' # matching : 4.7.0-0.microshift-2021-07-07-002815 - 4.8.0-0.microshift-2022-01-06-210147

jobs:  
  trigger_copr_repo_build:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:35
    steps:
      - shell: bash # git must be present before checkout
        run: sudo dnf install -y copr-cli golang gcc make systemd policycoreutils rpm-build git which podman

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: tars
        shell: bash
        run: ./packaging/images/components/archive.sh
